# GitHub Pages Configuration
title: Rules Generator
description: Sistema de geração de documentação modular para desenvolvimento de software
author: Allan Santos
url: https://allansantos-dv.github.io
baseurl: /rules

# GitHub Pages Settings
theme: null
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Build Settings
source: .
destination: _site
# Serve raw files from docs/ directory
keep_files:
  - docs/
  - assets/docs/

# Don't process these files as Jekyll pages
exclude:
  - node_modules
  - vendor
  - .git
  - .gitignore
  - README.md
  - .github

include:
  - docs/
  - assets/
  - index.html
  - preview.html
  - _layouts/
  - _includes/

# Default Layout
defaults:
  - scope:
      path: ""
    values:
      layout: default

# SEO Settings
seo:
  type: Website
  locale: pt_BR
  twitter:
    creator: "@AllanSantos-DV"
  facebook:
    app_id: ""

# Custom Settings
rules_generator:
  version: "1.0.0"
  last_updated: "2025-01-18"
  supported_domains:
    - backend
    - web
    - desktop
  github:
    username: "AllanSantos-DV"
    repository: "rules"

