# GitHub Pages Configuration - Static Site (No Jekyll)
title: Rules Generator
description: Sistema de geração de documentação modular para desenvolvimento de software
author: Allan Santos
url: https://allansantos-dv.github.io
baseurl: /rules

# Static site configuration (no Jekyll processing)
# All files will be served as-is due to .nojekyll file

# Custom Settings
rules_generator:
  version: "1.0.0"
  last_updated: "2025-01-18"
  supported_domains:
    - backend
    - web
    - desktop
  github:
    username: "AllanSantos-DV"
    repository: "rules"